"""
Django settings for simulator project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


import os
from dotenv import load_dotenv # type: ignore
from pathlib import Path
from django.contrib.messages import constants as messages


# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from the project root
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = ['10.252.7.5' , 'localhost', '127.0.0.1', 'web', 'nginx', '0.0.0.0']
# ALLOWED_HOSTS from environment: os.getenv('ALLOWED_HOST_Q')

# CSRF and CORS Settings for Docker deployment
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://web:8000',
    'http://nginx',
    'http://localhost',
    'http://127.0.0.1',
    'http://0.0.0.0:8000',
    'http://10.252.7.5:8000',
    'https://10.252.7.5:8000',
    'http://10.252.7.5',
]

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://localhost',
    'http://127.0.0.1',
    'http://10.252.7.5:8000',
    'https://10.252.7.5:8000',
    'http://10.252.7.5',
]

CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript to access CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'

LOGIN_URL = 'login'  # The name of your login view (if named 'login')

# Session timeout (in seconds)
SESSION_COOKIE_AGE = 1800  # Example: 30 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Application definition

INSTALLED_APPS = [
    'home.apps.HomeConfig',
    # "authentication.apps.AuthenticationConfig",
    "quantum_research.apps.QuantumResearchConfig",
    
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat', #Schedular for ingestion
    'corsheaders',  # CORS support
    'simulator'     #apps name      
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'home.middleware.PreventBackMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'simulator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simulator.wsgi.application'


# DATABASE (SQLite ONLY)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images) - served by Nginx in production
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files - served by Nginx in production
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "public/media"

# Email configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND_Q')
EMAIL_HOST = os.getenv('EMAIL_HOST_Q')
EMAIL_PORT = os.getenv('EMAIL_PORT_Q')
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER_Q')  # or 'sahrohit846@gmail.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD_Q')

# Email domain restriction
EMAIL_DOMAIN = os.getenv('EMAIL_DOMAIN_Q')  # Replace with your desired domain

# -------------------------
# MongoDB (MongoEngine)
# -------------------------
import config.mongo  # type: ignore - MongoDB connection 


# setup for Celery and redis 

CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_ENABLE_UTC = True
# this is the celery cacahe loking setup 
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_CACHE_URL", "redis://redis:6379/2"),
       
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
                          